apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP #prove um serviço pra permitir receber conexões internamente entre pods 
  selector:
    app: segundo-pod
  ports: 
    - port: 8080
      targetPort: 80
      